# This file was generated by GoReleaser. DO NOT EDIT.
cask "topoductor" do
  name "topoductor"
  desc "Terminal UI for managing git worktrees"
  homepage "https://github.com/brandonhsz/TopoDuctor"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "topoductor"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_darwin_amd64.tar.gz"
      sha256 "5ed4889418685350f1e7bf68909ce195d9189fcb960bd95d701cc1bc87a9bd1e"
    end
    on_arm do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_darwin_arm64.tar.gz"
      sha256 "f07ef01f96269e373287e4dde0e1a332c81886a5a5b0255598f41482ce90ba0f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_linux_amd64.tar.gz"
      sha256 "4955bac2a3df3117196909b5b3c1205eb736f7699466bb14334e3829d4abbd3d"
    end
    on_arm do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_linux_arm64.tar.gz"
      sha256 "01083b68fe91b9b018961be38d3fcf709eab9f34c632d27bdfcc0039529f1909"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/topoductor"]
    end
  end

  # No zap stanza required
end
