# This file was generated by GoReleaser. DO NOT EDIT.
cask "topoductor" do
  name "topoductor"
  desc "Terminal UI for managing git worktrees"
  homepage "https://github.com/brandonhsz/TopoDuctor"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "topoductor"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_darwin_amd64.tar.gz"
      sha256 "ea4fec28931d423c65feeadb2b250a9caa3928d014022af4d6fd2f7ea6ef6ae1"
    end
    on_arm do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_darwin_arm64.tar.gz"
      sha256 "57c99efdcafe5fdab61d137caca3422bff5e2db597657dcb5c1a26d3473b1b27"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_linux_amd64.tar.gz"
      sha256 "840bc80595977778f80af778f81d6a7d413b4e3f7d0795a2e76fdc2c35f42d59"
    end
    on_arm do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_linux_arm64.tar.gz"
      sha256 "08dc1e087213ba0e02bfa5d2daf0470820259e3f4d8401b9606772610d69adfc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/topoductor"]
    end
  end

  # No zap stanza required
end
