# This file was generated by GoReleaser. DO NOT EDIT.
cask "topoductor" do
  name "topoductor"
  desc "Terminal UI for managing git worktrees"
  homepage "https://github.com/brandonhsz/TopoDuctor"
  version "0.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "topoductor"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_darwin_amd64.tar.gz"
      sha256 "e32bd43ff7e0b3d13e5ed513018e30623b9a4847895ab258875d83f5fdf1631e"
    end
    on_arm do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_darwin_arm64.tar.gz"
      sha256 "d838d0cdfd25cae235db01d89906eebaecd5f1565cfce1bd9b755b17441349c4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_linux_amd64.tar.gz"
      sha256 "0d1a2a2fedee9d5a1e7b871a5e6c1bb211d4c57019ad0cd707deedf919d26acf"
    end
    on_arm do
      url "https://github.com/brandonhsz/TopoDuctor/releases/download/v#{version}/topoductor_#{version}_linux_arm64.tar.gz"
      sha256 "c65cc0c1e3fdacefb042aff5b4752c914ea260e0ec1d46b20e8945096fb32942"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/topoductor"]
    end
  end

  # No zap stanza required
end
